---
configure_terminal: yes
configure_osx: yes
configure_dotfiles: yes
configure_gpg: yes
configure_ssh: yes
configure_github_keys: yes
configure_github_enterprise_keys: yes

dotfiles_repo_local_destination: "{{ dotfiles_host_home }}/dotfiles"

# gitconfig_name: ""
# gitconfig_email: ""
# gitconfig_github_user: ""

# gpg_key_name: "{{ gitconfig_name }}"
# gpg_key_email: "{{ gitconfig_email }}"
# gpg_key_passphrase: ""

# ssh_key_comment: "{{ gitconfig_email }}"
# ssh_key_passphrase: ""
# github_gpg_key_title: "Mac DevOps GPG Key"
# github_ssh_key_title: "Mac DevOps SSH Key"
# github_enterprise_hostname: "github.example.com"
# github_enterprise_gpg_key_title: "Mac DevOps GPG Key"
# github_enterprise_ssh_key_title: "Mac DevOps SSH Key"

homebrew_installed_packages:
  # Dev
  - act
  - ansible
  - autoconf
  - automake
  - aws-iam-authenticator
  - azure-cli
  - bash
  - bash-completion@2
  - ca-certificates
  - coreutils
  - copilot
  - curl
  - dive
  - doctl
  - dyff
  - eksctl
  - gawk
  - gettext
  - gh
  - git
  - git-secret
  - gnu-getopt
  - gnu-sed
  - gnupg
  - gnutls
  - go
  - hashicorp/tap/terraform
  - hashicorp/tap/vault
  - helm
  - helmfile
  - homebrew/cask/hey
  - httperf
  - istioctl
  - jpeg
  - jq
  - k9s
  - kind
  - kompose
  - kops
  - kubernetes-cli
  - kube-ps1
  - kubeconform
  - kustomize
  - linode-cli
  - minikube
  - mas
  - moreutils
  - mpdecimal
  - mysql-client
  - pkg-config
  - nmap
  - node
  - nvm
  - openapi-generator
  - openjdk
  - openldap
  - php
  - pipx
  - pinentry-mac
  - pkg-config
  - podman
  - python
  - pytest
  - pyenv
  - qemu
  - readline
  - ripgrep
  - rsync
  - ruby
  - scw
  - shellcheck
  - skaffold
  - sops
  - sqlite
  - stern
  - terraform
  - tree
  - tmux
  - watch
  - wget
  - yarn
  - yq
  - zsh

homebrew_taps:
  - hashicorp/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - claude-code
  - docker
  - firefox
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - kap # Open-source screen recorder built with web technology
  - postman # Collaboration platform for API development
  - slack # Team communication and collaboration software
  - sourcetree # Graphical client for Git version control
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc # VLC media player

