---
- name: Ensure managed dotfiles directory exists.
  file:
    path: "{{ dotfiles_repo_local_destination }}"
    state: directory
    mode: "0755"
  become: no
  tags: dotfiles

- name: Copy configured dotfiles from local source into managed directory.
  copy:
    src: "{{ dotfiles_source_local }}/{{ item }}"
    dest: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    mode: preserve
  become: no
  loop: "{{ dotfiles_files | map('regex_replace', '/$', '') | reject('equalto', '.gitconfig') | list }}"
  tags: dotfiles

- name: Ensure managed dotfiles directory is a git repository.
  command: git init "{{ dotfiles_repo_local_destination }}"
  args:
    creates: "{{ dotfiles_repo_local_destination }}/.git"
  become: no
  tags: dotfiles

- name: Render templated .gitconfig into managed directory.
  template:
    src: gitconfig.j2
    dest: "{{ dotfiles_repo_local_destination }}/.gitconfig"
    mode: "0644"
  tags: dotfiles

- name: Link configured dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
    force: true
  become: no
  loop: "{{ (dotfiles_files | map('regex_replace', '/$', '') | list) + ['.gitconfig'] | unique }}"
  tags: dotfiles
